sonar.projectKey=0x0pointer_seraph
sonar.organization=0x0pointer

sonar.sources=app
sonar.tests=tests

sonar.exclusions=**/__pycache__/**,tools/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
